# create-react-doc configuration

# Site
title: Time Flying

# Menu dir
## you can also set detailed dir, such as BasicSkill/css
menu: [
  'React',
  'BasicSkill',
  'Algorithm',
  'FeCloud',
  'LeetCode',
  'Product'
]
## set init open menu keys
menuOpenKeys: /BasicSkill

# used theme
theme: crd-seed

# Github
## if you want to editing pages on github, you should config these arguments.
user: MuYunyun
repo: blog
branch: main              # the default value of branch is main
deploy_branch: gh-pages   # which branch to deploy.(default: gh-pages)
# publish:                # if you want upload to gitlab or other git platform, you can set full git url in it
github-ribbons: true
domain: https://muyunyun.cn
seo:
  google: true

# use search plugin: provide ability for searching site globally in the site.
# default value: true
# search: false
# host: 'muyunyun.cn'            # the url host to search
# search_map: {                  # search_map is connected to menu props
#   '/Algorithm': 'Algorithm',
#   '/BasicSkill': 'BasicSkill',
#   '/LeetCode': 'LeetCode',
#   '/React': 'React'
# }

# Available values: en | zh-cn
language: en

# Inject Custom Logic
inject: injectLogic.js